import type { StudentProfile } from './types';

export const seedStudent: StudentProfile = {
  name: 'Alex Rivera',
  year: 'First-year student, halfway through first semester',
  schoolContext:
    'Week 7 at Northview State; biology major with two lab sections, club soccer, work-study, and midterms stacking up.',
  privacyMode: 'Student-owned. Parents can pay, but content stays private unless shared.',
  demographics: {
    age: 18,
    campus: 'Northview State University',
    residence: 'Hawthorne Hall room 318',
    major: 'Biology',
    hometown: 'Cedar Falls, Iowa',
    chosenName: 'Alex',
    pronouns: 'they/them',
  },
  healthProfile: {
    conditions: [
      {
        name: 'ADHD, combined presentation',
        status: 'treated since high school',
        notes: 'Does best when medication, breakfast, and first class stay on a predictable rhythm.',
      },
      {
        name: 'Migraine without aura',
        status: 'intermittent',
        notes: 'Two late-week migraines this month, usually after poor sleep and skipped meals.',
      },
      {
        name: 'Exercise-induced bronchospasm history',
        status: 'remote but relevant with chest symptoms',
        notes: 'Had an albuterol inhaler in high school; not sure whether the dorm inhaler is current.',
      },
      {
        name: 'Left ankle sprain',
        status: 'improving',
        notes: 'Rolled ankle three weeks ago at club soccer. Sore after two practices this week.',
      },
    ],
    currentMedications: [
      {
        name: 'lisdexamfetamine',
        label: 'Stimulant prescription label',
        dose: '30 mg',
        schedule: '8:00 AM on class days',
        purpose: 'ADHD',
        refillStatus: '4 days left; prescriber approval may be needed before Friday',
      },
      {
        name: 'sumatriptan',
        label: 'Migraine rescue medication',
        dose: '50 mg',
        schedule: 'as needed for migraine, per prescription label',
        purpose: 'Migraine rescue',
        refillStatus: 'Enough supply for this month',
      },
      {
        name: 'ibuprofen',
        label: 'OTC pain reliever',
        dose: '400 mg',
        schedule: 'as needed, with food when possible',
        purpose: 'Headache or ankle soreness',
        refillStatus: 'Student supply in dorm',
      },
    ],
    allergies: ['amoxicillin - rash as a child'],
    immunizations: [
      { name: 'MMR', status: 'cleared', detail: 'Campus immunization record accepted.' },
      { name: 'Meningococcal ACWY', status: 'cleared', detail: 'Submitted during orientation.' },
      { name: 'Influenza', status: 'due this season', detail: 'Student health flu clinic starts next week.' },
    ],
    currentConcern: {
      summary: 'Cough after weekend tailgate, now fever and chest tightness worse since yesterday.',
      onset: 'Scratchy throat and cough started after Saturday tailgate; fever and chest tightness showed up Week 7 Monday night.',
      redFlags: [
        'chest tightness plus fever worse since yesterday',
        'resting heart rate running higher than baseline',
        'remote exercise-induced bronchospasm history',
      ],
      recentSelfCare: ['acetaminophen once last night', 'missed lunch before chemistry lab', 'slept under 6 hours three nights'],
      visitPrep: [
        'Bring stimulant prescription label and insurance card front image.',
        'Ask what symptoms should trigger urgent or emergency care.',
        'Ask whether class, lab, or soccer should be limited this week.',
      ],
    },
    carePreferences: [
      'Use Alex and they/them in care settings.',
      'Prefers urgent care over campus clinic after 6 PM.',
      'Does not want parent contact unless Alex asks first.',
      'Wants a short written symptom timeline before visits because recall gets worse when stressed.',
    ],
  },
  careTimeline: [
    {
      id: 'tailgate-last-month',
      when: 'Week 4 Saturday night',
      title: 'First tailgate went long',
      detail: 'Lost Sunday recovery time and asked for private, nonjudgmental party-safety support later.',
      source: 'student memory',
    },
    {
      id: 'ankle-sprain',
      when: 'Week 5 Tuesday',
      title: 'Rolled left ankle at club soccer',
      detail: 'Improving, but soreness returns after practice when sleep is low.',
      source: 'sports note',
    },
    {
      id: 'weekend-cough',
      when: 'Week 7 Saturday to Monday',
      title: 'Cough turned into fever and chest tightness',
      detail: 'Cough started after the tailgate; fever and chest tightness worsened Monday night and now affect lab and soccer decisions.',
      source: 'student report plus wearable trend',
    },
    {
      id: 'refill-window-opened',
      when: 'Week 7 Monday morning',
      title: 'Stimulant refill window opened',
      detail: 'Four days left. Prior authorization or prescriber approval can slow this down.',
      source: 'medication module',
    },
    {
      id: 'lab-lunch-misses',
      when: 'Weeks 6 and 7 Tuesdays/Thursdays',
      title: 'Chemistry lab keeps swallowing lunch',
      detail: 'Skipped lunch three lab days, followed by headaches or late-night food crashes.',
      source: 'routine memory',
    },
  ],
  wearableSummary: {
    lastSynced: 'Today at 7:12 AM from Apple Health demo import',
    sleep: '5h 42m average over the last 3 nights; bedtime shifted past 1:00 AM twice.',
    strain: 'Resting heart rate is up 9 bpm versus Alex baseline; HRV is down 18%.',
    recovery: 'Stress minutes are elevated on lab days and after late practices.',
    activity: 'Two club soccer practices this week plus normal campus walking; ankle soreness noted after practice.',
  },
  academicCalendar: [
    {
      id: 'bio-practical',
      when: 'Week 8 Monday',
      title: 'BIO 111 practical',
      type: 'exam',
      impact: 'Needs two focused study blocks, but not at the expense of symptom care.',
    },
    {
      id: 'chem-midterm',
      when: 'Week 8 Wednesday',
      title: 'CHEM 101 midterm',
      type: 'exam',
      impact: 'Exam cluster raises sleep debt and refill risk.',
    },
    {
      id: 'writing-draft',
      when: 'Week 8 Friday',
      title: 'Writing seminar draft',
      type: 'deadline',
      impact: 'Can be reduced to outline plus office-hours question if illness worsens.',
    },
    {
      id: 'work-study-shift',
      when: 'Week 7 Thursday evening',
      title: 'Library work-study shift',
      type: 'work',
      impact: 'May need coverage if fever continues.',
    },
  ],
  supportMap: [
    {
      name: 'Jordan',
      relationship: 'roommate',
      canHelpWith: 'rides, meals, quiet check-ins, pharmacy pickup if Alex asks',
      shareRule: 'Can know logistics, not symptoms or medication details unless Alex chooses.',
    },
    {
      name: 'Aunt Lena',
      relationship: 'trusted adult',
      canHelpWith: 'calm second opinion, insurance questions, parent pressure buffer',
      shareRule: 'Contact only after Alex explicitly opts in.',
    },
    {
      name: 'Sam',
      relationship: 'resident assistant',
      canHelpWith: 'campus resources, room concerns, urgent logistics',
      shareRule: 'Use for practical support, not private health details by default.',
    },
  ],
  familyContext: [
    'Parents are paying for THREAD and tuition but do not have access to student memory.',
    'Mom texts more when Alex sounds vague; Dad tends to call the school if he feels shut out.',
    'Best parent updates are boring, short, and logistics-only.',
  ],
  finances: {
    status: 'Work-study payday is Friday; dining dollars are tight until then.',
    openItems: ['Chemistry lab fee due this week', 'Dining shortfall on lab days', 'Possible urgent care copay'],
    parentBoundary: 'Can ask parents for payment help without exposing symptoms, medication, sexual health, or counseling details.',
  },
  insurance: {
    carrier: 'BlueCross parent plan',
    plan: 'PPO student dependent coverage',
    studentHealthCenter: 'Northview Student Health, East Campus Clinic',
    preferredPharmacy: 'Campus Corner Pharmacy',
    missingItems: ['Back of insurance card', 'Member services phone number', 'Urgent care copay amount'],
  },
  memory: [
    'Week 7 at Northview State; first time managing college health, money, food, and classes without a parent calendar.',
    'Monday/Wednesday/Friday biology lecture at 9:10 AM; Tuesday/Thursday chemistry lab runs through lunch.',
    'Usually takes stimulant medication at 8:00 AM on class days and needs refill started before Friday.',
    'Gets behind when sleep drops under 6.5 hours for two nights, especially before lab practicals.',
    'Prefers urgent care over campus clinic after 6 PM and wants a short symptom history ready before going.',
    'Roommate Jordan can help with meals or rides; Aunt Lena is the trusted adult only after Alex says yes.',
    'Parents can pay for THREAD, but student memory and records stay private unless Alex shares them.',
    'Club soccer is important, but ankle soreness and late practices can wipe out recovery.',
  ],
  trustedContacts: ['Jordan - roommate', 'Aunt Lena - trusted adult', 'Sam - resident assistant'],
  activeModuleIds: [
    'executive-function',
    'sleep-burnout-academic-load',
    'medication-management',
    'care-navigation',
    'mental-health-safety',
  ],
  availableModuleIds: [
    'nutrition-patterns',
    'sexual-health-privacy',
    'substance-party-safety',
    'acute-illness-injury',
    'admin-insurance',
    'document-vault-records',
    'chronic-condition-support',
    'identity-sensitive-care',
    'sports-fitness-recovery',
    'financial-stress',
  ],
  signals: [
    {
      id: 'symptom-red-flag',
      label: 'Chest tightness plus fever note',
      value: 'worse since yesterday after weekend cough',
      severity: 'urgent',
    },
    {
      id: 'refill-window',
      label: 'Medication refill',
      value: '4 days left; prescriber approval may be needed',
      severity: 'high',
    },
    { id: 'sleep-debt', label: 'Sleep debt', value: '3 nights under 6.5 hours', severity: 'high' },
    {
      id: 'exam-cluster',
      label: 'Midterm cluster',
      value: 'bio practical, chem midterm, and writing draft in 5 days',
      severity: 'high',
    },
    { id: 'missed-meals', label: 'Lab-day meals', value: 'skipped lunch 3 lab days', severity: 'medium' },
    { id: 'party-risk', label: 'Weekend recovery', value: 'lost time at first tailgate last month', severity: 'medium' },
    {
      id: 'insurance-card',
      label: 'Insurance basics',
      value: 'front card uploaded; back and policy phone missing',
      severity: 'medium',
    },
    {
      id: 'record-sprawl',
      label: 'Records split',
      value: 'immunization PDF, receipts, and clinic note across photos/email',
      severity: 'medium',
    },
    { id: 'isolation', label: 'Check-in tone', value: 'roommate says Alex has been quieter this week', severity: 'medium' },
    { id: 'migraine-pattern', label: 'Stress headaches', value: 'two late-week migraines this month', severity: 'medium' },
    {
      id: 'identity-care-preference',
      label: 'Care preference',
      value: 'wants chosen name, pronouns, and privacy notes remembered',
      severity: 'medium',
    },
    { id: 'sports-recovery', label: 'Club soccer load', value: 'ankle soreness after two practices', severity: 'low' },
    { id: 'financial-stress', label: 'Money pressure', value: 'lab fee and dining shortfall due before payday', severity: 'medium' },
  ],
  documents: [
    { id: 'insurance', title: 'Insurance card', kind: 'Card', status: 'Front captured, back missing' },
    { id: 'rx', title: 'Stimulant prescription label', kind: 'Medication', status: 'Captured' },
    { id: 'immunization', title: 'Immunization record', kind: 'Campus form', status: 'Cleared' },
    { id: 'health-intake', title: 'Campus health intake form', kind: 'Campus form', status: 'Needs signature' },
    { id: 'sports-clearance', title: 'Club sports clearance', kind: 'Campus form', status: 'Due before tournament' },
    { id: 'lab-fee', title: 'Chemistry lab fee receipt', kind: 'Receipt', status: 'Needs review' },
  ],
};
