import type { StudentProfile } from './types';

export const seedStudent: StudentProfile = {
  name: 'Alex Rivera',
  year: 'First-year student, halfway through first semester',
  schoolContext:
    'Week 7 at Northview State; biology major with two lab sections, club soccer, work-study, and midterms stacking up.',
  privacyMode: 'Student-owned. Parents can pay, but content stays private unless shared.',
  memory: [
    'Week 7 at Northview State; first time managing college health, money, food, and classes without a parent calendar.',
    'Monday/Wednesday/Friday biology lecture at 9:10 AM; Tuesday/Thursday chemistry lab runs through lunch.',
    'Usually takes stimulant medication at 8:00 AM on class days and needs refill started before Friday.',
    'Gets behind when sleep drops under 6.5 hours for two nights, especially before lab practicals.',
    'Prefers urgent care over campus clinic after 6 PM and wants a short symptom history ready before going.',
    'Roommate Jordan can help with meals or rides; Aunt Lena is the trusted adult only after Alex says yes.',
    'Parents can pay for THREAD, but student memory and records stay private unless Alex shares them.',
    'Club soccer is important, but ankle soreness and late practices can wipe out recovery.',
  ],
  trustedContacts: ['Jordan - roommate', 'Aunt Lena - trusted adult', 'Sam - resident assistant'],
  activeModuleIds: [
    'executive-function',
    'sleep-burnout-academic-load',
    'medication-management',
    'care-navigation',
    'mental-health-safety',
  ],
  availableModuleIds: [
    'nutrition-patterns',
    'sexual-health-privacy',
    'substance-party-safety',
    'acute-illness-injury',
    'admin-insurance',
    'document-vault-records',
    'chronic-condition-support',
    'identity-sensitive-care',
    'sports-fitness-recovery',
    'financial-stress',
  ],
  signals: [
    {
      id: 'symptom-red-flag',
      label: 'Chest tightness plus fever note',
      value: 'worse since yesterday after weekend cough',
      severity: 'urgent',
    },
    {
      id: 'refill-window',
      label: 'Medication refill',
      value: '4 days left; prescriber approval may be needed',
      severity: 'high',
    },
    { id: 'sleep-debt', label: 'Sleep debt', value: '3 nights under 6.5 hours', severity: 'high' },
    {
      id: 'exam-cluster',
      label: 'Midterm cluster',
      value: 'bio practical, chem midterm, and writing draft in 5 days',
      severity: 'high',
    },
    { id: 'missed-meals', label: 'Lab-day meals', value: 'skipped lunch 3 lab days', severity: 'medium' },
    { id: 'party-risk', label: 'Weekend recovery', value: 'lost time at first tailgate last month', severity: 'medium' },
    {
      id: 'insurance-card',
      label: 'Insurance basics',
      value: 'front card uploaded; back and policy phone missing',
      severity: 'medium',
    },
    {
      id: 'record-sprawl',
      label: 'Records split',
      value: 'immunization PDF, receipts, and clinic note across photos/email',
      severity: 'medium',
    },
    { id: 'isolation', label: 'Check-in tone', value: 'roommate says Alex has been quieter this week', severity: 'medium' },
    { id: 'migraine-pattern', label: 'Stress headaches', value: 'two late-week migraines this month', severity: 'medium' },
    {
      id: 'identity-care-preference',
      label: 'Care preference',
      value: 'wants chosen name, pronouns, and privacy notes remembered',
      severity: 'medium',
    },
    { id: 'sports-recovery', label: 'Club soccer load', value: 'ankle soreness after two practices', severity: 'low' },
    { id: 'financial-stress', label: 'Money pressure', value: 'lab fee and dining shortfall due before payday', severity: 'medium' },
  ],
  documents: [
    { id: 'insurance', title: 'Insurance card', kind: 'Card', status: 'Front captured, back missing' },
    { id: 'rx', title: 'Stimulant prescription label', kind: 'Medication', status: 'Captured' },
    { id: 'immunization', title: 'Immunization record', kind: 'Campus form', status: 'Cleared' },
    { id: 'health-intake', title: 'Campus health intake form', kind: 'Campus form', status: 'Needs signature' },
    { id: 'sports-clearance', title: 'Club sports clearance', kind: 'Campus form', status: 'Due before tournament' },
    { id: 'lab-fee', title: 'Chemistry lab fee receipt', kind: 'Receipt', status: 'Needs review' },
  ],
};
